version: "3"
services:
  db:
    image: mysql:8.0
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: warehouse
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 2s
      retries: 5
  warehouse:
    image: warehouse:latest
    depends_on:
      db:
        condition: service_healthy
    ports:
    - 8081:8081
    # for metrics endpoint
    - 8088:8088
    # remote debug port
    - 5005:5005
    environment:
      - spring.datasource.host=db
      - spring.datasource.port=3306
      - spring.datasource.username=user
      - spring.datasource.password=password